"""initial schema

Revision ID: 52ea37938544
Revises: 
Create Date: 2026-09-01 20:05:03.626676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ea37938544'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('esrb_rating', sa.String(length=10), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("esrb_rating IN ('EC', 'E', 'E10+', 'T', 'M', 'AO', 'RP')", name='ck_games_esrb_rating'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_title'), 'games', ['title'], unique=False)
    op.create_table('password_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('game_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('box_art', 'screenshot')", name='ck_game_images_kind'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_images_game_id'), 'game_images', ['game_id'], unique=False)
    op.create_table('user_game_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ownership_type', sa.String(length=20), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("ownership_type IN ('digital', 'physical')", name='ck_user_game_library_ownership_type'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_game_library_user_game')
    )
    op.create_index(op.f('ix_user_game_library_game_id'), 'user_game_library', ['game_id'], unique=False)
    op.create_index(op.f('ix_user_game_library_user_id'), 'user_game_library', ['user_id'], unique=False)
    op.create_table('user_game_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_library_id', sa.Integer(), nullable=False),
    sa.Column('graphics_performance', sa.SmallInteger(), nullable=True),
    sa.Column('music_sound', sa.SmallInteger(), nullable=True),
    sa.Column('controls_playability', sa.SmallInteger(), nullable=True),
    sa.Column('content_length', sa.SmallInteger(), nullable=True),
    sa.Column('fun_factor', sa.SmallInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('content_length IS NULL OR content_length BETWEEN 0 AND 10', name='ck_reviews_content_length_range'),
    sa.CheckConstraint('controls_playability IS NULL OR controls_playability BETWEEN 0 AND 10', name='ck_reviews_controls_playability_range'),
    sa.CheckConstraint('fun_factor IS NULL OR fun_factor BETWEEN 0 AND 10', name='ck_reviews_fun_factor_range'),
    sa.CheckConstraint('graphics_performance IS NULL OR graphics_performance BETWEEN 0 AND 10', name='ck_reviews_graphics_performance_range'),
    sa.CheckConstraint('music_sound IS NULL OR music_sound BETWEEN 0 AND 10', name='ck_reviews_music_sound_range'),
    sa.ForeignKeyConstraint(['user_library_id'], ['user_game_library.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_library_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_reviews')
    op.drop_index(op.f('ix_user_game_library_user_id'), table_name='user_game_library')
    op.drop_index(op.f('ix_user_game_library_game_id'), table_name='user_game_library')
    op.drop_table('user_game_library')
    op.drop_index(op.f('ix_game_images_game_id'), table_name='game_images')
    op.drop_table('game_images')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('password_credentials')
    op.drop_index(op.f('ix_games_title'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('systems')
    # ### end Alembic commands ###
