"""add admin role and game approval

Revision ID: 60beed0891d8
Revises: cde52421e7fe
Create Date: 2026-09-26 22:21:06.092494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60beed0891d8'
down_revision: Union[str, Sequence[str], None] = 'cde52421e7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_approved', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('games', 'is_approved')
    # ### end Alembic commands ###
